### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by TareqAldirawi** [aangelopoulos/conformal-risk#1]
Hi, 
I am trying to run the code and I cannot run it since I cannot see the pre-trained model for the ZOO.
Where can I get the code for it? I appreciate the help.
Best wishes,
Tareq

**Comment by aangelopoulos** [comment]
Which example are you talking about?

**Comment by TareqAldirawi** [comment]
The FNR control in multilabel classification. You used ASL.

**Comment by aangelopoulos** [comment]
This should be the link to the model: https://github.com/Alibaba-MIIL/ASL/blob/main/MODEL_ZOO.md

**Comment by aangelopoulos** [comment]
We used the TResNet-XL
